import os


#accounts =os.listdir("./Accounts")
#accounts = accounts[:abs(len(accounts))]

with open("index.html","w") as f:
    f.write("""
<html>
<head>
<title>Viewer of Images .Generated By ISCLI</title>
</head>
<body>""")
    """
    for (root,_,fns),acc in zip(os.walk(os.getcwd()+"/Accounts/"),accounts):
        f.write(f"<div align=center style='text-align:center'><h2>{acc}</h2>")
        for fn in fns:
            path = f"Accounts/{acc}/{fn}"
            print(f"Adding {path} to index.html")
            f.write(f"<a href={path} target='_blank' style='margin:4px;border:1px solid black;border-radius:4px'><img src='{path}' width=200 height=200></a>")
        f.write("</div>")
    f.write("</body></html>")"""
    for i in os.listdir("Accounts/"):
        f.write(f"<div align=center style='text-align:center'><h2>{i}</h2>")
        for o in os.listdir("Accounts/"+i):
            path = "Accounts/"+i+"/"+o
            f.write(f"<a href={path.replace(' ','%20')} target='_blank' style='margin:4px'><img style='border:1px solid black;border-radius:4px' src='{path}' width=200 height=200></a>")
        f.write("</div>")
    f.write("</body></html>")
print("Done")

            
